import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IconAngular, IconCSS, IconFirebase, IconGit, IconHTML, IconJavaScript, IconMaterialDesign, IconReact, IconRestApi, IconScrum, IconTypeScript, IconVue } from './technologies/technologies.component';
import { IconEmail, IconEmailLight, IconGitHub, IconGitHubLight, IconLinkedIn, IconLinkedInLight } from './links/links.component';
import { ImgEllipse1, ImgEllipse1Hover, ImgEllipse2, ImgEllipse2Hover, ImgEllipse3, ImgEllipse4, ImgEllipse5, ImgEllipse6, ImgEllipse7, ImgEllipse8 } from './backgrounds/backgrounds.component';
import { IconEmail1, IconPhone, IconPortfolio, ImgArrow, ImgBulletPoint, ImgBurgerMenu, ImgCheckbox, ImgLocation, ImgLocation1 } from './other/other.component';

@NgModule({
  declarations: [
    IconAngular,
    IconTypeScript,
    IconHTML,
    IconCSS,
    IconJavaScript,
    IconFirebase,
    IconMaterialDesign,
    IconScrum,
    IconRestApi,
    IconEmail,
    IconGitHub,
    IconLinkedIn,
    ImgEllipse1,
    ImgEllipse1Hover,
    ImgArrow,
    ImgBurgerMenu,
    ImgEllipse2,
    ImgEllipse2Hover,
    IconPortfolio,
    IconEmail1,
    IconPhone,
    ImgEllipse3,
    ImgEllipse4,
    ImgLocation,
    ImgLocation1,
    IconReact,
    IconVue,
    ImgEllipse5,
    ImgEllipse6,
    IconGit,
    ImgBulletPoint,
    ImgEllipse7,
    ImgCheckbox,
    IconEmailLight,
    IconGitHubLight,
    IconLinkedInLight,
    ImgEllipse8
  ],
  imports: [CommonModule],
  exports: [
    IconAngular,
    IconTypeScript,
    IconHTML,
    IconCSS,
    IconJavaScript,
    IconFirebase,
    IconMaterialDesign,
    IconScrum,
    IconRestApi,
    IconEmail,
    IconGitHub,
    IconLinkedIn,
    ImgEllipse1,
    ImgEllipse1Hover,
    ImgArrow,
    ImgBurgerMenu,
    ImgEllipse2,
    ImgEllipse2Hover,
    IconPortfolio,
    IconEmail1,
    IconPhone,
    ImgEllipse3,
    ImgEllipse4,
    ImgLocation,
    ImgLocation1,
    IconReact,
    IconVue,
    ImgEllipse5,
    ImgEllipse6,
    IconGit,
    ImgBulletPoint,
    ImgEllipse7,
    ImgCheckbox,
    IconEmailLight,
    IconGitHubLight,
    IconLinkedInLight,
    ImgEllipse8
  ]
})
export class SvgImageModule {}